server:
  port: 7080
  servlet:
    context-path:
spring:
  application:
    name: relation
  datasource:
    url: jdbc:h2:file:./h2DB;FILE_LOCK=SOCKET
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl