server:
  port: 7080
  servlet:
    context-path:
spring:
  application:
    name: relation
  datasource:
    url: jdbc:h2:~/default
    username: root
    password: root
    driver-class-name: org.h2.Driver
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    suffix: .ftl
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl